### ISSUE TITLE
Change search categories.

### ISSUE THREAD

**Issue by marek2001** [moa-engine/MOA#32]
I would like to hide some search categories because it feels too clustered if there are too many categories which i never used. Only a few of people use categories like Q&A or social media.

**Comment by mehr32** [comment]
Hello. The reason for dividing the categories into smaller sections was to attempt to merge the results if needed (for example, if you searched for 'travel to Malaysia,' part of the results would come from the 'map' category). However, due to the complexity of the base code (searxng), this will not be implemented in the current version and will be implemented in the rewrite. (MOA is going to be rewritten from scratch.) Thank you for reminding me; I will reduce the number of categories in the next version (probably similar to searxng's settings).

**Comment by marek2001** [comment]
Thanks, for your answer. I will be waiting for new version.
